name: Playwright Tests
on:
  push:
    branches: capstone/299171-Salman-Benny
  pull_request:
    branches: capstone/299171-Salman-Benny
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      working-directory: Playwright_Automation_Final
      run: npm ci

    - name: Install Playwright Browsers
      working-directory: Playwright_Automation_Final
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      working-directory: Playwright_Automation_Final
      env:
        BASE_URL: ${{ secrets.SALMAN_BASE_URL }}
      run: npx playwright test paymentSuccess.spec.ts
      

    - name: Upload Playwright Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: Playwright_Automation_Final/playwright-report/
        retention-days: 30
